version: "2"
services:
  app:
    tty: true
    stdin_open: true
    depends_on:
      - 'mongo'
    container_name: app
    restart: always
    image: 629517020360.dkr.ecr.eu-west-1.amazonaws.com/ecr-vacationer-backend
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: 'mongo:5.0.11'
    ports:
      - "27017:27017"
    volumes: 
      - 'mongo:/data/db'
volumes:
  mongo: