version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
    - MONGO_INITDB_DATABASE=vacation-data
    volumes: 
      - ./data:/data/db
      - ./initial_data:/docker-entrypoint-initdb.d
